{
 "title": "Company Employee Count",
 "tags": [ "custom" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "company",
    "label": "Company",
    "query": {
     "query": "label_values(users_count_by_company,company_name)"
    }
   },
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(users_count_by_country,country_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$company",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_count_by_company{company_name=~\"$company\", country_name=~\"$country\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(users_total{company_name=~\"$company\", country_name=~\"$country\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(users_deleted_total{company_name=~\"$company\", country_name=~\"$country\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}