{
 "title": "RED Dashboard",
 "description": "RED Dashboard tracking application metrics",
 "tags": [ "Ravn" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{instance=\"$instance\",uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{instance=\"$instance\"}) / sum by(uri)(http_server_requests_seconds_count{instance=\"$instance\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"$instance\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percent of 2xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{instance=\"$instance\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{instance=\"$instance\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{instance=\"$instance\", status!~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{instance=\"$instance\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{method}} {{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Percent of 4xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{ instance=\"$instance\", status=~\"4.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{ instance=\"$instance\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Percent of 5xx Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(uri) (http_server_requests_seconds_count{ instance=\"$instance\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{ instance=\"$instance\", uri!=\"/actuator/prometheus\"})",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\",  exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{instance=\"$instance\", exception=\"none\",uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "PR 99 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "PR 95 Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  }
 ]
}