{
 "title": "GraphQL RED Dashboard",
 "description": "GraphQL RED Dashboard tracking operations metrics",
 "tags": [
  "Ravn",
  "GraphQL"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "operation_name",
    "label": "Operation Name",
    "query": {
     "query": "label_values(graphql_operations_seconds_count, operation_name)"
    }
   },
   {
    "name": "operation_type",
    "label": "Operation Type",
    "query": {
     "query": "label_values(graphql_operations_seconds_count, operation_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Operations Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphql_operations_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Total Ops/sec"
    }
   ]
  },
  {
   "title": "Total Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphql_operations_seconds_count{instance=\"$instance\", outcome!=\"SUCCESS\"}[1m]))",
     "legendFormat": "Errors/sec"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphql_operations_seconds_sum{instance=\"$instance\"}[1m])) / sum(rate(graphql_operations_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(graphql_operations_seconds_count{instance=\"$instance\", outcome!=\"SUCCESS\"}[1m])) / sum(rate(graphql_operations_seconds_count{instance=\"$instance\"}[1m]))) * 100",
     "legendFormat": "Error %"
    }
   ]
  },
  {
   "title": "Operations Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(operation_type, operation_name) (graphql_operations_seconds_count{instance=\"$instance\", operation_type=~\"$operation_type\",operation_name=~\"$operation_name\"})",
     "legendFormat": "{{operation_type}} - {{operation_name}}"
    }
   ]
  },
  {
   "title": "Operations Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(operation_name)(graphql_operations_seconds_sum{instance=\"$instance\", operation_name=~\"$operation_name\"}) / sum by(operation_name)(graphql_operations_seconds_count{instance=\"$instance\", operation_name=~\"$operation_name\"})",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations Rate by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(operation_type)(rate(graphql_operations_seconds_count{instance=\"$instance\", operation_type=~\"$operation_type\"}[1m]))",
       "legendFormat": "{{operation_type}}"
      }
     ]
    },
    {
     "title": "Operations Rate by Outcome",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(outcome)(rate(graphql_operations_seconds_count{instance=\"$instance\"}[1m]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "Operations Rate by Name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(operation_name)(rate(graphql_operations_seconds_count{instance=\"$instance\", operation_name=~\"$operation_name\"}[1m]))",
       "legendFormat": "{{operation_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate by Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(operation_name) (graphql_operations_seconds_count{instance=\"$instance\", outcome!=\"SUCCESS\", operation_name=~\"$operation_name\"}) / sum by(operation_name) (graphql_operations_seconds_count{instance=\"$instance\", operation_name=~\"$operation_name\"})",
       "legendFormat": "{{operation_name}}"
      }
     ]
    },
    {
     "title": "Errors by Phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(phase)(rate(graphql_operations_seconds_count{instance=\"$instance\", outcome!=\"SUCCESS\"}[1m]))",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Client vs Server Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(outcome)(rate(graphql_operations_seconds_count{instance=\"$instance\", outcome!=\"SUCCESS\"}[1m]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Percentiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(le)(rate(graphql_operations_seconds_bucket{instance=\"$instance\", operation_name=~\"$operation_name\", operation_type=~\"$operation_type\"}[1m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le)(rate(graphql_operations_seconds_bucket{instance=\"$instance\", operation_name=~\"$operation_name\", operation_type=~\"$operation_type\"}[1m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le)(rate(graphql_operations_seconds_bucket{instance=\"$instance\", operation_name=~\"$operation_name\", operation_type=~\"$operation_type\"}[1m])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Latency by Operation Type (p95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation_type)(rate(graphql_operations_seconds_bucket{instance=\"$instance\", operation_type=~\"$operation_type\"}[1m])))",
       "legendFormat": "{{operation_type}} (p95)"
      }
     ]
    },
    {
     "title": "Latency by Operation Name (p95)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation_name)(rate(graphql_operations_seconds_bucket{instance=\"$instance\", operation_name=~\"$operation_name\"}[1m])))",
       "legendFormat": "{{operation_name}}"
      }
     ]
    }
   ]
  }
 ]
}