apiVersion: 1
contactPoints:
    - orgId: 1
      name: slack-alerts
      receivers:
        - uid: cf6sfbnxi9ssgf
          type: slack
          settings:
            url: ${SLACK_WEBHOOK_URL}
          disableResolveMessage: false
